spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:auth_db}
    username: ${DB_USER:auth}
    password: ${DB_PASSWORD:authpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

  logging:
    level:
      root: INFO
      org.hibernate.SQL: DEBUG

  server:
    port: ${SERVER_PORT:8080}

