spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:dev_secret_change_me}
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 2592000000

logging:
  level:
    root: DEBUG